### ISSUE TITLE
Hello , I have some problem.... can u help me?

### ISSUE THREAD

**Issue by Rabbitbeer** [YECHEZ/wow-fish-bot#5]
frame = cv2.cvtColor(img_np, cv2.COLOR_BGR2RGB)
TypeError: Expected Ptr<cv::UMat> for argument '%s'

this error 

how can i fix?

**Comment by YECHEZ** [comment]
> frame = cv2.cvtColor(img_np, cv2.COLOR_BGR2RGB)
> TypeError: Expected Ptrcv::UMat for argument '%s'
> 
> this error
> 
> how can i fix?

1. Try to debug what the **img_np** variable returns. I think for some reason the variable returns None
2. Try to replace: 
`frame = cv2.cvtColor(img_np, cv2.COLOR_BGR2RGB)`
to:
`frame = cv2.cvtColor(cv2.UMat(img_np), cv2.COLOR_BGR2RGB)`
