### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by GentrifiedBeefNoodle** [YECHEZ/wow-fish-bot#6]
Hello! I downloaded and scanned the EXE, and have it running along side the game now. 

It autocasts the '1' ability and when it 'splashes' the mouse moves, but it moves in a totally weird direction, not towards the bobber at all. I've tried 1920x1080 Maximised and 800x600 windowed and it doesn't seem to follow the fishing bobber. If I unhide my UI it finds my abilities and clicks those! but it wont find the bobber, it just moves to the bottom right or far left of my screen.

any pointers?

**Comment by YECHEZ** [comment]
Can you try to run this via python using source code?

**Comment by GentrifiedBeefNoodle** [comment]
I'll learn what you mean and give it a go :)

**Comment by GentrifiedBeefNoodle** [comment]
I think I'm too stupid to get this working via python :) Thanks anyhow.

**Comment by YECHEZ** [comment]
Thanks for feedback. I would like to get more information but unfortunately will have to work with what is

**Comment by GentrifiedBeefNoodle** [comment]
So I run it in python but it failed on finding a module

![image](https://user-images.githubusercontent.com/56235602/66990670-91147400-f0be-11e9-827c-b8c8c2bade27.png)

**Comment by GentrifiedBeefNoodle** [comment]
Ahh, ok, I think I have to download and configure a bunch of dependencies/modules from other sources, correct? 

I think this goes beyond my understanding as an absolute layman (I've never used Python before and am coming in to this as a 100% novice). 

I managed to (I think?!) get past the pyautogui error as pictured by placing the module in the FBO directory but it errors now on numpy and this module seems far more complex to install. 

Again, thanks anyway, and all the best.

**Comment by YECHEZ** [comment]
The easiest way is to install from the file _requirements.txt_ using pip
`pip install -r /path/to/requirements.txt`

**Comment by GentrifiedBeefNoodle** [comment]
I see, this is interesting, learning every day!

I get an error durng installation of the requirements however:

ERROR: Could not find a version that satisfies the requirement opencv-python==4.1.0.25 (from -r C:/Users/NAME/Desktop/FBo/requirements.txt (line 3)) (from versions: none)
ERROR: No matching distribution found for opencv-python==4.1.0.25 (from -r C:/Users/NAME/Desktop/FBo/requirements.txt (line 3))

**Comment by CKNOEP** [comment]
use python 3.7 instead of 3.8
after
run -> pip install -r /path/to/requirements.txt
and 
run -> the programm.

Optional
I modified the following code, in the original version the fish is not looted,
Line 126
                            #pyautogui.keyDown('shiftleft')
                            #pyautogui.mouseDown(button='right')
                            pyautogui.click(button='right')
                            #pyautogui.mouseUp(button='right')

**Comment by GentrifiedBeefNoodle** [comment]
Well this seems to have solved it, thanks CKNOEP! I ran 3.7, installed pip, ran it against the requirements and launched the exe after and bingo! Thanks very much :) 

edit: it worked without the optional modified code. I only had to disable auto-loot in-game to allow the bot to do that bit.
